server {
    listen 80;

    root /usr/share/nginx/html;
    index super-mario-world.html;

    types {
        application/wasm wasm;
        application/javascript js;
        application/octet-stream data;
    }

    location / {
        try_files $uri $uri/ /super-mario-world.html;
    }

    add_header Cross-Origin-Opener-Policy same-origin;
    add_header Cross-Origin-Embedder-Policy require-corp;
}
