unordered = [
    "turn",
    "question",
    "hidden-question",
    "note",
    "brown",
    "grey",
    "ice",
    "cloud",
    "music",
    "spike",
    "falling-0",
    "unbreakable",
    "castle-floor",
    "iced-coin",
    "coin",
]

pipes = [
    "green-pipe-flat-0-0",
    "green-pipe-flat-1-0",
    "green-pipe-flat-2-0",
    "green-pipe-flat-0-1",
    "green-pipe-flat-1-1",
    "green-pipe-flat-2-1",

    "green-pipe-tall-0-0",
    "green-pipe-tall-1-0",
    "green-pipe-tall-0-1",
    "green-pipe-tall-1-1",
    "green-pipe-tall-0-2",
    "green-pipe-tall-1-2",

    "yellow-pipe-flat-0-0",
    "yellow-pipe-flat-1-0",
    "yellow-pipe-flat-2-0",
    "yellow-pipe-flat-0-1",
    "yellow-pipe-flat-1-1",
    "yellow-pipe-flat-2-1",

    "yellow-pipe-tall-0-0",
    "yellow-pipe-tall-1-0",
    "yellow-pipe-tall-0-1",
    "yellow-pipe-tall-1-1",
    "yellow-pipe-tall-0-2",
    "yellow-pipe-tall-1-2",

    "blue-pipe-flat-0-0",
    "blue-pipe-flat-1-0",
    "blue-pipe-flat-2-0",
    "blue-pipe-flat-0-1",
    "blue-pipe-flat-1-1",
    "blue-pipe-flat-2-1",

    "blue-pipe-tall-0-0",
    "blue-pipe-tall-1-0",
    "blue-pipe-tall-0-1",
    "blue-pipe-tall-1-1",
    "blue-pipe-tall-0-2",
    "blue-pipe-tall-1-2",

    "red-pipe-flat-0-0",
    "red-pipe-flat-1-0",
    "red-pipe-flat-2-0",
    "red-pipe-flat-0-1",
    "red-pipe-flat-1-1",
    "red-pipe-flat-2-1",

    "red-pipe-tall-0-0",
    "red-pipe-tall-1-0",
    "red-pipe-tall-0-1",
    "red-pipe-tall-1-1",
    "red-pipe-tall-0-2",
    "red-pipe-tall-1-2",
]

semisolid = [
    "semisolid-0-0-0",
    "semisolid-0-1-0",
    "semisolid-0-2-0",
    "semisolid-0-0-1",
    "semisolid-0-1-1",
    "semisolid-0-2-1",

    "semisolid-1-0-0",
    "semisolid-1-1-0",
    "semisolid-1-2-0",
    "semisolid-1-0-1",
    "semisolid-1-1-1",
    "semisolid-1-2-1",
    "semisolid-1-0-2",
    "semisolid-1-1-2",
    "semisolid-1-2-2",
    "semisolid-1-0-3",
    "semisolid-1-1-3",
    "semisolid-1-2-3",

    "semisolid-2-0-0",
    "semisolid-2-1-0",
    "semisolid-2-2-0",
    "semisolid-2-0-1",
    "semisolid-2-1-1",
    "semisolid-2-2-1",
    "semisolid-2-0-2",
    "semisolid-2-1-2",
    "semisolid-2-2-2",
]

mushrooms = [
    "red-mushroom-0",
    "red-mushroom-1",
    "red-mushroom-2",

    "green-mushroom-0",
    "green-mushroom-1",
    "green-mushroom-2",

    "yellow-mushroom-0",
    "yellow-mushroom-1",
    "yellow-mushroom-2",

    "bridge-0",
    "bridge-1",

    "half-stem-0",
    "half-stem-1",

    "stem",
]

decorations = [
    "belt-0",
    "belt-1",
    "belt-2",

    "flower-0-0",
    "flower-1-0",
    "flower-1-1",
    "flower-2-0",
    "flower-2-1",
    "flower-2-2",

    "bush-0",
    "bush-1",
    "bush-2",

    "vines-0",
    "vines-1",
    "vines-2",
]

ground = [
    "ground-00000000",
    "ground-00000010",
    "ground-00001000",
    "ground-00001010",
    "ground-00001011",
    "ground-00010000",
    "ground-00010010",
    "ground-00010110",
    "ground-00011000",
    "ground-00011010",
    "ground-00011011",
    "ground-00011110",
    "ground-00011111",
    "ground-01000000",
    "ground-01000010",
    "ground-01001000",
    "ground-01001010",
    "ground-01001011",
    "ground-01010000",
    "ground-01010010",
    "ground-01010110",
    "ground-01011000",
    "ground-01011010",
    "ground-01011011",
    "ground-01011110",
    "ground-01011111",
    "ground-01101000",
    "ground-01101010",
    "ground-01101011",
    "ground-01111000",
    "ground-01111010",
    "ground-01111011",
    "ground-01111110",
    "ground-01111111",
    "ground-11010000",
    "ground-11010010",
    "ground-11010110",
    "ground-11011000",
    "ground-11011010",
    "ground-11011011",
    "ground-11011110",
    "ground-11011111",
    "ground-11111000",
    "ground-11111010",
    "ground-11111011",
    "ground-11111110",
    "ground-11111111",
]

# _ = [
#     "falling-1",
#     "red-coin",
#     "turning-1",
#     "turning-2",
#     "turning-3",
#     "belt-right-0-1",
#     "belt-right-1-1",
#     "belt-right-2-1",
#     "belt-left-0-1",
#     "belt-left-1-1",
#     "belt-left-2-1",
#     "belt-right-0-0",
#     "belt-right-1-0",
#     "belt-right-2-0",
#     "belt-left-0-0",
#     "belt-left-1-0",
#     "belt-left-2-0",
#     "red-belt-right-0-1",
#     "red-belt-right-1-1",
#     "red-belt-right-2-1",
#     "red-belt-left-0-1",
#     "red-belt-left-1-1",
#     "red-belt-left-2-1",
#     "on-red",
#     "on-blue",
#     "red-belt-right-0-0",
#     "red-belt-right-1-0",
#     "red-belt-right-2-0",
#     "red-belt-left-0-0",
#     "red-belt-left-1-0",
#     "red-belt-left-2-0",
#     "off-red",
#     "off-blue",
#     "on-off-red",
#     "on-off-blue",
#     "red-belt-0",
#     "red-belt-1",
#     "red-belt-2",
#     "blue-belt-0",
#     "blue-belt-1",
#     "blue-belt-2",
#     "blue-belt-right-0-1",
#     "blue-belt-right-1-1",
#     "blue-belt-right-2-1",
#     "blue-belt-left-0-1",
#     "blue-belt-left-1-1",
#     "blue-belt-left-2-1",
#     "stable-icicle-1",
#     "blue-belt-right-0-0",
#     "blue-belt-right-1-0",
#     "blue-belt-right-2-0",
#     "blue-belt-left-0-0",
#     "blue-belt-left-1-0",
#     "blue-belt-left-2-0",
#     "stable-icicle-0",
#     "falling-icicle-1",
#     "falling-icicle-0",
#     "p-open",
#     "p-closed",
# ]
