default-width = 16
default-height = 16

air = { x = 1, y = 23 }
turn = { x = 18, y = 23 }
question = { x = 35, y = 23 }
hidden-question = { x = 52, y = 23 }
note = { x = 69, y = 23 }
brown = { x = 86, y = 23 }
grey = { x = 103, y = 23 }
coin = { x = 123, y = 23, width = 10 }
belt-0 = { x = 137, y = 23 }
belt-1 = { x = 154, y = 23 }
belt-2 = { x = 171, y = 23 }
green-pipe-flat-0-1 = { x = 188, y = 23 }
green-pipe-flat-1-1 = { x = 205, y = 23 }
green-pipe-flat-2-1 = { x = 222, y = 23 }
green-pipe-tall-0-2 = { x = 239, y = 23 }
green-pipe-tall-1-2 = { x = 256, y = 23 }
flower-0-0 = { x = 1, y = 40 }
flower-1-1 = { x = 18, y = 40 }
flower-1-0 = { x = 35, y = 40 }
flower-2-2 = { x = 52, y = 40 }
flower-2-1 = { x = 69, y = 40 }
flower-2-0 = { x = 86, y = 40 }
half-stem-0 = { x = 103, y = 40 }
half-stem-1 = { x = 120, y = 40 }
green-pipe-flat-0-0 = { x = 188, y = 40 }
green-pipe-flat-1-0 = { x = 205, y = 40 }
green-pipe-flat-2-0 = { x = 222, y = 40 }
green-pipe-tall-0-1 = { x = 239, y = 40 }
green-pipe-tall-1-1 = { x = 256, y = 40 }
bridge-0 = { x = 1, y = 57 }
red-mushroom-0 = { x = 52, y = 57 }
red-mushroom-1 = { x = 69, y = 57 }
red-mushroom-2 = { x = 86, y = 57 }
green-pipe-tall-0-0 = { x = 239, y = 57 }
green-pipe-tall-1-0 = { x = 256, y = 57 }
bridge-1 = { x = 1, y = 74 }
yellow-mushroom-0 = { x = 52, y = 74 }
yellow-mushroom-1 = { x = 69, y = 74 }
yellow-mushroom-2 = { x = 86, y = 74 }
stem = { x = 103, y = 74 }
semisolid-0-0-1 = { x = 120, y = 74 }
semisolid-0-1-1 = { x = 137, y = 74 }
semisolid-0-2-1 = { x = 154, y = 74 }
semisolid-1-0-3 = { x = 171, y = 74 }
semisolid-1-1-3 = { x = 188, y = 74 }
semisolid-1-2-3 = { x = 205, y = 74 }
semisolid-2-0-2 = { x = 222, y = 74 }
semisolid-2-1-2 = { x = 239, y = 74 }
semisolid-2-2-2 = { x = 256, y = 74 }
falling-0 = { x = 1, y = 91 }
falling-1 = { x = 18, y = 91 }
spike = { x = 35, y = 91 }
green-mushroom-0 = { x = 52, y = 91 }
green-mushroom-1 = { x = 69, y = 91 }
green-mushroom-2 = { x = 86, y = 91 }
semisolid-0-0-0 = { x = 120, y = 91 }
semisolid-0-1-0 = { x = 137, y = 91 }
semisolid-0-2-0 = { x = 154, y = 91 }
semisolid-1-0-2 = { x = 171, y = 91 }
semisolid-1-1-2 = { x = 188, y = 91 }
semisolid-1-2-2 = { x = 205, y = 91 }
semisolid-2-0-1 = { x = 222, y = 91 }
semisolid-2-1-1 = { x = 239, y = 91 }
semisolid-2-2-1 = { x = 256, y = 91 }
music = { x = 103, y = 108 }
semisolid-1-0-1 = { x = 171, y = 108 }
semisolid-1-1-1 = { x = 188, y = 108 }
semisolid-1-2-1 = { x = 205, y = 108 }
cloud = { x = 103, y = 125 }
semisolid-1-0-0 = { x = 171, y = 125 }
semisolid-1-1-0 = { x = 188, y = 125 }
semisolid-1-2-0 = { x = 205, y = 125 }
semisolid-2-0-0 = { x = 222, y = 125 }
semisolid-2-1-0 = { x = 239, y = 125 }
semisolid-2-2-0 = { x = 256, y = 125 }
ice = { x = 137, y = 142 }
ground-00011111-0 = { x = 154, y = 142 }
ground-00010110-0 = { x = 171, y = 142 }
ground-00001011-0 = { x = 188, y = 142 }
ground-00011111-1 = { x = 205, y = 142 }
vines-0 = { x = 222, y = 142 }
vines-1 = { x = 239, y = 142 }
vines-2 = { x = 256, y = 142 }
ground-11111111-0 = { x = 154, y = 159 }
ground-11010110-0 = { x = 171, y = 159 }
ground-01101011-0 = { x = 188, y = 159 }
ground-11111111-1 = { x = 205, y = 159 }
bush-0 = { x = 222, y = 159 }
bush-1 = { x = 239, y = 159 }
bush-2 = { x = 256, y = 159 }
ground-00001011-1 = { x = 137, y = 210 }
ground-00010110-1 = { x = 154, y = 210 }
ground-01101011-1 = { x = 171, y = 210 }
ground-11010110-1 = { x = 188, y = 210 }
ground-01101000-0 = { x = 205, y = 210 }
ground-11010000-0 = { x = 222, y = 210 }
ground-00011000-0 = { x = 239, y = 210 }
ground-00011000-1 = { x = 256, y = 210 }
ground-00011000-2 = { x = 1, y = 227 }
ground-00011111-2 = { x = 18, y = 227 }
ground-00011111-3 = { x = 35, y = 227 }
ground-00011111-4 = { x = 52, y = 227 }
ground-11111111-2 = { x = 69, y = 227 }
ground-11111111-3 = { x = 86, y = 227 }
ground-11111111-4 = { x = 103, y = 227 }
ground-11111000-0 = { x = 120, y = 227 }
ground-11111000-1 = { x = 137, y = 227 }
ground-11111000-2 = { x = 154, y = 227 }
ground-01101011-2 = { x = 171, y = 227 }
ground-01101011-3 = { x = 188, y = 227 }
ground-01101011-4 = { x = 205, y = 227 }
ground-11010110-2 = { x = 222, y = 227 }
ground-11010110-3 = { x = 239, y = 227 }
ground-11010110-4 = { x = 256, y = 227 }
ground-00000000-0 = { x = 1, y = 244 }
ground-00001000-0 = { x = 18, y = 244 }
ground-00011000-3 = { x = 35, y = 244 }
ground-00010000-0 = { x = 52, y = 244 }
ground-00000010-0 = { x = 69, y = 244 }
ground-01000010-0 = { x = 86, y = 244 }
ground-01000000-0 = { x = 103, y = 244 }
ground-01010000-0 = { x = 120, y = 244 }
ground-01001000-0 = { x = 137, y = 244 }
ground-00010010-0 = { x = 154, y = 244 }
ground-00001010-0 = { x = 171, y = 244 }
ground-01011000-0 = { x = 188, y = 244 }
ground-00011010-0 = { x = 205, y = 244 }
ground-01010010-0 = { x = 222, y = 244 }
ground-01001010-0 = { x = 239, y = 244 }
ground-01011010-0 = { x = 256, y = 244 }
ground-01001011-0 = { x = 1, y = 261 }
ground-01010110-0 = { x = 18, y = 261 }
ground-01101010-0 = { x = 35, y = 261 }
ground-11010010-0 = { x = 52, y = 261 }
ground-00011011-0 = { x = 69, y = 261 }
ground-00011110-0 = { x = 86, y = 261 }
ground-01111000-0 = { x = 103, y = 261 }
ground-11011000-0 = { x = 120, y = 261 }
ground-01011011-0 = { x = 137, y = 261 }
ground-01011110-0 = { x = 154, y = 261 }
ground-01111010-0 = { x = 171, y = 261 }
ground-11011010-0 = { x = 188, y = 261 }
ground-01011111-0 = { x = 205, y = 261 }
ground-11111010-0 = { x = 222, y = 261 }
ground-01111011-0 = { x = 239, y = 261 }
ground-11011110-0 = { x = 256, y = 261 }
ground-11011011-0 = { x = 1, y = 278 }
ground-01111110-0 = { x = 18, y = 278 }
ground-00011111-5 = { x = 52, y = 278 }
ground-00010110-2 = { x = 69, y = 278 }
ground-01101011-5 = { x = 86, y = 278 }
ground-11111111-5 = { x = 103, y = 278 }
ground-11010110-5 = { x = 120, y = 278 }
ground-01101000-1 = { x = 137, y = 278 }
ground-11111000-3 = { x = 154, y = 278 }
ground-11010000-1 = { x = 171, y = 278 }
ground-01111111-0 = { x = 188, y = 278 }
ground-11011111-0 = { x = 205, y = 278 }
ground-11111011-0 = { x = 222, y = 278 }
ground-11111110-0 = { x = 239, y = 278 }
castle-floor = { x = 256, y = 278 }
red-coin = { x = 1, y = 295 }
turning-1 = { x = 18, y = 295 }
turning-2 = { x = 35, y = 295 }
turning-3 = { x = 52, y = 295 }
belt-right-0-1 = { x = 69, y = 295 }
belt-right-1-1 = { x = 86, y = 295 }
belt-right-2-1 = { x = 103, y = 295 }
belt-left-0-1 = { x = 120, y = 295 }
belt-left-1-1 = { x = 137, y = 295 }
belt-left-2-1 = { x = 154, y = 295 }
iced-coin = { x = 1, y = 312 }
belt-right-0-0 = { x = 69, y = 312 }
belt-right-1-0 = { x = 86, y = 312 }
belt-right-2-0 = { x = 103, y = 312 }
belt-left-0-0 = { x = 120, y = 312 }
belt-left-1-0 = { x = 137, y = 312 }
belt-left-2-0 = { x = 154, y = 312 }
red-belt-right-0-1 = { x = 69, y = 363 }
red-belt-right-1-1 = { x = 86, y = 363 }
red-belt-right-2-1 = { x = 103, y = 363 }
red-belt-left-0-1 = { x = 120, y = 363 }
red-belt-left-1-1 = { x = 137, y = 363 }
red-belt-left-2-1 = { x = 154, y = 363 }
on-red = { x = 35, y = 380 }
on-blue = { x = 52, y = 380 }
red-belt-right-0-0 = { x = 69, y = 380 }
red-belt-right-1-0 = { x = 86, y = 380 }
red-belt-right-2-0 = { x = 103, y = 380 }
red-belt-left-0-0 = { x = 120, y = 380 }
red-belt-left-1-0 = { x = 137, y = 380 }
red-belt-left-2-0 = { x = 154, y = 380 }
off-red = { x = 35, y = 397 }
off-blue = { x = 52, y = 397 }
on-off-red = { x = 35, y = 414 }
on-off-blue = { x = 52, y = 414 }
red-pipe-flat-0-1 = { x = 69, y = 431 }
red-pipe-flat-1-1 = { x = 86, y = 431 }
red-pipe-flat-2-1 = { x = 103, y = 431 }
red-belt-0 = { x = 171, y = 431 }
red-belt-1 = { x = 188, y = 431 }
red-belt-2 = { x = 205, y = 431 }
red-pipe-flat-0-0 = { x = 69, y = 448 }
red-pipe-flat-1-0 = { x = 86, y = 448 }
red-pipe-flat-2-0 = { x = 103, y = 448 }
yellow-pipe-flat-0-1 = { x = 1, y = 652 }
yellow-pipe-flat-1-1 = { x = 18, y = 652 }
yellow-pipe-flat-2-1 = { x = 35, y = 652 }
blue-pipe-flat-0-1 = { x = 52, y = 652 }
blue-pipe-flat-1-1 = { x = 69, y = 652 }
blue-pipe-flat-2-1 = { x = 86, y = 652 }
red-pipe-tall-0-2 = { x = 103, y = 652 }
red-pipe-tall-1-2 = { x = 120, y = 652 }
yellow-pipe-tall-0-2 = { x = 137, y = 652 }
yellow-pipe-tall-1-2 = { x = 154, y = 652 }
blue-pipe-tall-0-2 = { x = 171, y = 652 }
blue-pipe-tall-1-2 = { x = 188, y = 652 }
red-pipe-tall-0-0 = { x = 205, y = 652 }
red-pipe-tall-1-0 = { x = 222, y = 652 }
yellow-pipe-tall-0-0 = { x = 239, y = 652 }
yellow-pipe-tall-1-0 = { x = 256, y = 652 }
yellow-pipe-flat-0-0 = { x = 1, y = 669 }
yellow-pipe-flat-1-0 = { x = 18, y = 669 }
yellow-pipe-flat-2-0 = { x = 35, y = 669 }
blue-pipe-flat-0-0 = { x = 52, y = 669 }
blue-pipe-flat-1-0 = { x = 69, y = 669 }
blue-pipe-flat-2-0 = { x = 86, y = 669 }
red-pipe-tall-0-1 = { x = 103, y = 669 }
red-pipe-tall-1-1 = { x = 120, y = 669 }
yellow-pipe-tall-0-1 = { x = 137, y = 669 }
yellow-pipe-tall-1-1 = { x = 154, y = 669 }
blue-pipe-tall-0-1 = { x = 171, y = 669 }
blue-pipe-tall-1-1 = { x = 188, y = 669 }
blue-pipe-tall-0-0 = { x = 205, y = 669 }
blue-pipe-tall-1-0 = { x = 222, y = 669 }
unbreakable = { x = 239, y = 669 }
blue-belt-0 = { x = 1, y = 686 }
blue-belt-1 = { x = 18, y = 686 }
blue-belt-2 = { x = 35, y = 686 }
blue-belt-right-0-1 = { x = 52, y = 686 }
blue-belt-right-1-1 = { x = 69, y = 686 }
blue-belt-right-2-1 = { x = 86, y = 686 }
blue-belt-left-0-1 = { x = 103, y = 686 }
blue-belt-left-1-1 = { x = 120, y = 686 }
blue-belt-left-2-1 = { x = 137, y = 686 }
stable-icicle-1 = { x = 256, y = 686 }
blue-belt-right-0-0 = { x = 52, y = 703 }
blue-belt-right-1-0 = { x = 69, y = 703 }
blue-belt-right-2-0 = { x = 86, y = 703 }
blue-belt-left-0-0 = { x = 103, y = 703 }
blue-belt-left-1-0 = { x = 120, y = 703 }
blue-belt-left-2-0 = { x = 137, y = 703 }
stable-icicle-0 = { x = 256, y = 703 }
falling-icicle-1 = { x = 256, y = 720 }
falling-icicle-0 = { x = 256, y = 737 }
p-open = { x = 1, y = 771 }
p-closed = { x = 18, y = 771 }
